[versions]
accompanistSystemuicontroller = "0.28.0"
agp = "8.7.3"
androidTools = "31.5.0"
firebaseBom = "33.1.2"
googleCloudTexttospeech = "2.0.1"
kotlin = "2.1.0"
compose = "1.5.4"
compose-compiler = "1.5.4"
compose-material3 = "1.1.2"
compose-plugin = "1.7.1"
androidx-activityCompose = "1.8.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
ktor = "2.3.13"
material = "1.10.0"
generative-ai = "0.5.0-1.0.0"
buildKonfig = "0.15.2"
kmpViewModel = "2.8.0"
jetbrainsKotlinJvm = "2.1.0"
navigation = "2.8.4"
coil = "3.0.4"
datetime = "0.6.0"
serialization-json = "1.7.3"

room = "2.7.0-alpha05"
ksp = "2.1.0-1.0.29"
peekaboo = "0.5.2"
koin = "4.0.0"
materialKolor = "2.0.0"
google-services = "4.4.2"
composeIcons = "1.1.1"
androidxComposeBom = "2024.06.00"
sqliteBundled = "2.5.0-alpha05"

eungabi = "0.3.1"
urlencoder = "1.6.0"

decompose = "3.0.0"
fileket = "0.8.7"
[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqliteBundled" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
google-cloud-texttospeech = { module = "com.google.cloud:google-cloud-texttospeech", version.ref = "googleCloudTexttospeech" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json"}

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
kmp-viewmodel = {module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "kmpViewModel"}
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation"}
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation"}


androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-gradle-plugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

eungabi = { module = "io.github.easternkite:eungabi", version.ref = "eungabi"}
urlencoder = { module = "net.thauvin.erik.urlencoder:urlencoder-lib", version.ref = "urlencoder"}

materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

coil-core = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin"}
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin"}
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin"}
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin"}

generativeAi = { module = "dev.shreyaspatil.generativeai:generativeai-google", version.ref = "generative-ai" }

composeIcons-tablerIcons = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "composeIcons" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "fileket"}

# :build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-multiplatformPlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-plugin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

google-services = { id = "com.google.gms.google-services", version.ref = "google-services"}



# Convention Plugins
brocallie-android-application-compose = { id = "brocallie.android.application.compose" }
brocallie-compose-multiplatform-shared = { id = "brocallie.compose.multiplatform.shared" }
brocallie-kotlin-multiplatform-shared = { id = "brocallie.kotlin.multiplatform.shared" }
brocallie-core-designsystem = { id = "brocallie.core.designsystem" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }